In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.__version__

'2.2.3'

In [3]:
url = "https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv"

df = pd.read_csv(url)

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
len(df)

10000

In [6]:
df['fuel_type'].nunique()

3

In [7]:
df.isnull().any().sum()

np.int64(2)

In [8]:
df.isnull().sum().sum()

np.int64(1141)

In [10]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

41.2

In [11]:
df['horsepower'].median()

254.0

In [12]:
df['horsepower'].describe()

count    9123.000000
mean      254.446016
std        22.844613
min       171.000000
25%       239.000000
50%       254.000000
75%       270.000000
max       334.000000
Name: horsepower, dtype: float64

In [13]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [14]:
#fill missing values

df['horsepower'] = df['horsepower'].fillna(252)

In [15]:
df['horsepower'].median()

252.0

In [16]:
asia = df[df['origin'] == 'Asia']

In [17]:
asia.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,252.0,4420,19.5,26.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4

In [18]:
asia_7 = asia[['vehicle_weight', 'model_year']].head(7)

In [19]:
asia_7

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [21]:
#convert to array

X = asia_7.values

In [22]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [23]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [24]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [25]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [26]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [27]:
w.sum()

np.float64(0.36919696904927535)